---
name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  spec-ubuntu:
    name: Spec - ubuntu ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', 'head', 'jruby-head']

    steps:
      - uses: actions/checkout@v4
      - name: Install and setup tor
        run: |
          sudo apt-get install -y tor
          tor --versioncd
          pidof tor
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run specs
        run: bundle exec rspec
